export const enum ActionsTodo {
  ADD_TODO = "ADD_TODO",
  REMOVE_TODO = "REMOVE_TODO",
  LOAD_TODOS = "LOAD_TODOS",
  UPDATE_TODO = "UPDATE_TODO",
  TOGGLE_TODO = "TOGGLE_TODO",
  SET_LOADING = "SET_LOADING",
  SET_ERROR = "SET_ERROR",
}
