import { Layout } from "@/presentation/components";
import { TodoView } from "@/presentation/view/todo-view/todo-view.component";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Clean Arc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Layout>
        <TodoView />
      </Layout>
    </>
  );
}
